version: "3.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-server
    environment:
      - REDIS_URL=redis://redis-instance
      - PORT=3001
    ports:
      - 3001:3001
    volumes:
      - .:/app
    depends_on:
      - redis
    command: npm run server-dev

  worker:
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: image-worker
    environment:
        - NODE_ENV=development
        - PORT=3000
        - REDIS_URL=redis://redis-instance
    volumes:
        - .:/app
    depends_on:
        - redis
    command: npm run worker-dev
  
  test:
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: test-container
    environment:
        - NODE_ENV=development
        - PORT=3000
        - REDIS_URL=redis://redis-instance
    volumes:
        - .:/app
    depends_on:
        - redis
    entrypoint: ["echo", "Test container disabled"]
    # Enable to run tests
    # command: npm t

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    container_name: redis-instance
    ports:
      - '6379:6379'